### PR TITLE
Add JSON-P TCK module

### LINKED ISSUE #5: Add JSON-P TCK module
To run the TCK basically needs the following:
- Change the _tck/bin/ts.jte_ to include the classes of the implementation
- Run `ant run.all` in the _tck/src/com/sun/ts/ts/tests/jsonp_ folder

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #5

To run, you can use `mvn verify -P tck -pl tck`

For now, it is needed to run the TCK with JDK 8 to pass the signature test.

### CODE REVIEW

**Comment by leadpony** [comment]
@Thihup 
Thank you a lot.
I do not know why but in my environment there found 6 failures in the TCK. :sweat_smile:

**Comment by Thihup** [comment]
There are 5 issues that are actually "issues". The last one is the signature test. It will only pass by now if you use JDK 8 to run it.
It is the last test on the list.

**Comment by Thihup** [comment]
Let me explain it more clearly:
The signature tests verify if the API is correct, with all the required classes.
It uses both static and runtime analysis.
As we are using the API from Jakarta it is already correct. However, the JDK itself changed some classes (have added some interfaces to Enum, have changed the @Deprecated annotation, etc) and it makes it fail the runtime test.

For now, the best way is to run with JDK 8 to pass the signature test. There is support for running with JDK 11 but needs to change a little bit to use the ts.jte.jdk11 instead of the ts.jte.

**Comment by leadpony** [comment]
@Thihup 
As you told me, I got correct test results when running the TCK with JDK 8.
You are awesome.

**Pull request merged**
